spring:
  application:
    name: task-service
  jackson:
    default-property-inclusion: NON_NULL
  config:
    import: optional:.env[.properties]
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP-SERVERS}
  data:
    mongodb:
      authentication-database: ${SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE}
      username: ${SPRING_DATA_MONGODB_USERNAME}
      password: ${SPRING_DATA_MONGODB_PASSWORD}
      port: ${SPRING_DATA_MONGODB_PORT}
      database: ${SPRING_DATA_MONGODB_DATABASE}
      host: ${SPRING_DATA_MONGODB_HOST}
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
server:
  port: 8080

settings:
  requirementProducer: kafka/requirementProducer.xml
  taskConsumer: kafka/taskConsumer.xml